#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS
FILENAME="/etc/passwd"

while IFS= read -r line

do

  echo "$line"
  
done < $FILENAME